# Site settings
title: Hyun Choi
name: Hyun Choi
position: Undergraduate Student · Yonsei University
email: chlgusla1@yonsei.ac.kr
description: |
  AI · Computer Vision · Reinforcement Learning  
  Interested in autonomous driving, medical imaging, and robust AI.
baseurl: "" # leave empty since this is a user site
url: "https://choihyun-1110.github.io" # your GitHub Pages URL

# Social / external links
twitter_username: ""   # 없으면 비워둬도 됨
github_username: choihyun-1110
google_scholar: ""     # Scholar 프로필 있으면 ID 넣기
linkedin: "hyun1110"   # LinkedIn 프로필 있으면 추가

# Analytics (optional)
google_analytics: ""   # GA 쓰려면 추후에 코드 넣기

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact
